### ISSUE TITLE
Create ips/bps?

### ISSUE THREAD

**Issue by trebrick** [Wh0ba/XPatcher#2]
Is there a way to create an ips/bps file from the original and patched rom like in flips? Also, love not having to use terminal and flips on my phone to patch anymore, Thanks!

**Comment by Wh0ba** [comment]
Hey there, Thanks for your great feedback.
I’ve added the ability to create patches using original ROMs and the modified ROMs 
It was kinda messy lol, since I had to make sure to still look and feel the same and be easy to use
I have also tested it by patching a rom then creating a patch from the patched version 
Then trying it out and it worked 100% the same 
I still have some final touches on the UX side, hopefully I can push the update sometime today.

**Comment by trebrick** [comment]
Talk about fast lol i cant even imagine what it takes to get everything looking good let alone working. Anyway, awesome cant wait to test it out!

**Comment by Wh0ba** [comment]
I've added all the necessary code and hopefully it will work and look nice as intended,
And published a new release with all the changes and the .ipa and .deb for XPatcher.
Thanks for the kind request, I really needed something to code on since summer break just started for us College students lol.ヽ(✿ﾟ▽ﾟ)ノ
Have a great day .

**Comment by trebrick** [comment]
Works like a charm and looks great! Again, thisll save me so much time not having to mess with terminal and flips on my phone and typing out unnecessarily long rom names/paths. Make adding things to my appletv more efficient too! Thanks for the hard work, keep it up, and enjoy your summer break!
